org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# Opt out of new DSL temporarily
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
# Configure Gradle to use JDK 17
org.gradle.java.home=C:\\Program Files\\Java\\jdk-17
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
